FROM maven:3.9.11-amazoncorretto-21-debian-trixie AS build

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY . .

RUN mvn clean package -DskipTests

FROM openjdk:21-slim
#FROM tomcat:10.1-jdk21-temurin

WORKDIR /app
#WORKDIR /usr/local/tomcat/webapps

COPY --from=build /app/ ./
#COPY --from=build /app/target/*.war ROOT.war

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
#CMD ["catalina.sh", "run"]
